#  Build & Run FHIR Publisher, and push output to FHIR Current Build publication servers

langauge: java

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'

script: ./build.sh
sudo: required
notifications:
  email: []
  webhooks:
    - https://chat.fhir.org/api/v1/external/travis?stream=committers&topic=ci-notifications&api_key=IelOy1KhccEy3QpRIeOrtQUTqw98Kvr8

before_install:
  - openssl aes-256-cbc -K $encrypted_7d142fa10e4e_key -iv $encrypted_7d142fa10e4e_iv -in deploy.build.fhir.org.enc -out ~/deploy.build.fhir.org -d
  - chmod 600 ~/deploy.build.fhir.org

after_success:
  - cd publish
  - echo -e "Host build.fhir.org\n  Compression yes\n  StrictHostKeyChecking no\n  User fhir_upload\n  IdentityFile ~/deploy.build.fhir.org" > ~/.ssh/config
  - tar czf - * | ssh -p 2222 build.fhir.org ./publish
